services:
  portal-server:
    build: .      
    ports:
      - '3000:3000'
    depends_on:
      - portal-db
      - portal-app
    # Лучше вообще убрать отсюда DATABASE_URL, если сервер сам берёт .env!

  portal-db:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
  portal-app:
    build: ../client-portal
    ports: 
      - '80:80'
